Added rule for max and min password length
HackAtUCI/quill pull request #170
Opened 2018-10-28 07:22 UTC by kbuci

Added check in angular frontend to check bounds of password, so that client can know the password is invalid before sending the application form data to  /auth/register and getting a password size error.

2018-10-30 04:44 UTC, chriswongtv requested changes

2018-10-30 04:44 UTC, chriswongtv commented on app/client/views/apply/applyCtrl.js
> +                  prompt: 'Your password needs to have at least 6 characters'
```suggestion
                  prompt: 'Your password needs to have at least 6 characters.'
```

2018-10-30 04:44 UTC, chriswongtv commented on app/client/views/apply/applyCtrl.js
> +                  prompt: 'Your password is too long'
```suggestion
                  prompt: 'Your password needs to have at most 64 characters.'
```

2018-11-05 03:20 UTC, Jeremyyang920 requested changes
Change the majors back to the dropdown

2018-11-06 08:30 UTC, chriswongtv requested changes
Just some minor changes then you’re good to go!

2018-11-06 08:30 UTC, chriswongtv commented on app/client/views/apply/applyCtrl.js
> +                  prompt: 'Please type your major.'
Let’s revert this change since you’re continuing to use a drop down menu for major selection

2018-11-06 08:30 UTC, chriswongtv commented on app/server/controllers/UserController.js
> +    if (!validator.isEmail(email)){
```suggestion
    if (!validator.isEmail(email)) {
```

2018-11-06 08:30 UTC, chriswongtv commented on app/server/controllers/UserController.js
> +        message: "Not a valid email."
Use single quotes for strings

2018-11-06 08:30 UTC, chriswongtv commented on app/server/controllers/UserController.js
> +    /* Disabling whitelist feature
Feel free to remove this code altogether

2018-11-06 15:24 UTC, Jeremyyang920 commented
Looks good to me after chris' comments

2018-11-07 00:36 UTC, Jeremyyang920 approved these changes

2018-11-07 04:29 UTC, Jeremyyang920 approved these changes

2018-11-07 04:30 UTC, merged