Fix reset password
HackAtUCI/quill pull request #185
Opened 2018-11-25 22:01 UTC by leinerf

it inherits styling from login so I just took out the div and add the spinning anteater logo

2018-11-25 22:05 UTC, leinerf commented
I formatted the doc too

2018-11-27 01:19 UTC, chriswongtv requested changes

2018-11-27 01:19 UTC, chriswongtv commented on app/client/stylesheets/_login.scss
> +<<<<<<< HEAD
fix merge conflicts

2018-11-27 02:00 UTC, chriswongtv approved these changes

2018-11-27 02:01 UTC, merged