Apply page
HackAtUCI/quill pull request #31
Opened 2017-10-28 04:10 UTC by chriswongtv

2017-10-28 05:17 UTC, Jeremyyang920 commented
Can we indicate which questions on the application are mandatory.

2017-10-28 06:24 UTC, chriswongtv commented
@Jeremyyang920 done

2017-10-28 16:38 UTC, Jeremyyang920 commented
Can you use this page here
https://www.admissions.uci.edu/study/programs.php
and select engineering, physical sciences and ICS and update our current list of majors. I want to make sure to have the engineering fields in there or like math and physics majors.

2017-10-28 21:06 UTC, chriswongtv commented
@Jeremyyang920 done

2017-10-28 22:15 UTC, madhavgharmalkar requested changes

2017-10-28 22:15 UTC, madhavgharmalkar commented on app/client/views/application/application.html
> +              <option value="others">Others</option>
Change this to other

2017-10-28 22:15 UTC, madhavgharmalkar commented on app/client/views/application/application.html
> +              <option value="others">Others</option>
Change 'Others' to 'Other'

2017-10-28 22:16 UTC, chriswongtv commented on app/client/views/application/application.html
> +              <option value="others">Others</option>
@madhavgharmalkar done

2017-10-29 18:09 UTC, madhavgharmalkar approved these changes

2017-10-29 18:09 UTC, merged